//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Kutuphane.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mvc_Kutuphane.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string benihatirla {
            get {
                return ResourceManager.GetString("benihatirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BENİM SAYFAM.
        /// </summary>
        public static string benimsayfam {
            get {
                return ResourceManager.GetString("benimsayfam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string giriş {
            get {
                return ResourceManager.GetString("giriş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KİTAP SEPETİM.
        /// </summary>
        public static string kitapsepetim {
            get {
                return ResourceManager.GetString("kitapsepetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı veya Email.
        /// </summary>
        public static string kullaniciadimail {
            get {
                return ResourceManager.GetString("kullaniciadimail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KÜTÜPHANE.
        /// </summary>
        public static string kutuphane {
            get {
                return ResourceManager.GetString("kutuphane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFİL.
        /// </summary>
        public static string profil {
            get {
                return ResourceManager.GetString("profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAROLAMI UNUTTUM.
        /// </summary>
        public static string prolaunutum {
            get {
                return ResourceManager.GetString("prolaunutum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to şifre.
        /// </summary>
        public static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜYE OL.
        /// </summary>
        public static string uyeol {
            get {
                return ResourceManager.GetString("uyeol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YÖNETİM.
        /// </summary>
        public static string yonetim {
            get {
                return ResourceManager.GetString("yonetim", resourceCulture);
            }
        }
    }
}
